import Head from "next/head";
import { getContentfulClient } from "../services/contentfulHelper";
import Landing  from "@/components/landing";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Bayada R&D Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing listItems={props.items}></Landing>
    </>
  );
}

export async function getServerSideProps() {
  let data = {};
  await getContentfulClient(false)
    .getEntries()
    .then((res) => (data = res))
    .catch((error) => {
      data = error;
    });
  return {
    props: data,
  };
}
