import Head from "next/head";
import { getContentfulClient } from "../services/contentfulHelper";
import JsonRender from "@/components/jsonRender/json-render";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Bayada R&D Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Landing listItems={props.items}></Landing> */}
      <JsonRender articleData={props.data.items} />
    </>
  );
}

export async function getServerSideProps() {
  let data = await getContentfulClient(false, "Develop")
    .getEntries()
    .then((res) => res)
    .catch((error) => error);
  return {
    props: { data },
  };
}
